version: '2'
services:
  bazels3cache:
    image: "gcr.io/tink-containers/bazels3cache:latest"
    environment:
      - S3_BUCKET=tink-bazel-cache-build-staging
  app:
    image: "gcr.io/tink-containers/bazel:${BAZEL_IMAGE_TAG:-3.7.2.16}"
    working_dir: /tink-backend
    links:
      - bazels3cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - ..:/bazel-hello
      - /var/lib/buildkite-agent/.cache/bazel:/root/.cache/bazel
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /bazel-remote-cache:/cache
      - /var/lib/buildkite-agent/git-mirrors:/var/lib/buildkite-agent/git-mirrors:ro
      - /var/lib/buildkite-agent/.config/coursier/credentials.properties:/root/.config/coursier/credentials.properties
    environment:
      - SSH_AUTH_SOCK
      - VERSION
      - BUILDKITE
      - CI
      - BUILDKITE_LABEL
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_COMMIT
      - BUILDKITE_MESSAGE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_ORGANIZATION_SLUG
      - TINK_REPO_UPLOAD_ACCESS_KEY_ID
      - TINK_REPO_UPLOAD_SECRET_ACCESS_KEY
      - GOOGLE_CLOUD_ACCOUNT_JSON
      - SONAR_TOKEN
      - MODE
      - COMPOSE_HTTP_TIMEOUT
